baseURL = 'https://n-kase.github.io/rss/'
languageCode = 'ja-jp'
title = 'ms02 AI Assistant Blog Posts Project'
theme = 'stack'
publishDir = 'docs' # GitHub Pages設定に合わせて明記

[params]
  mainSections = ["posts"]
  [params.sidebar]
    emoji = "⚡"
    subtitle = "MS-02 Ultra Home Lab"
    avatar = false
    # サイドバーにウィジェットを常に表示する設定
    # widgets = ["search", "archives", "categories", "tags"]

  [[params.widgets.homepage]]
    type = "search"
  [[params.widgets.homepage]]
    type = "archives"
  [[params.widgets.homepage]]
    type = "categories"
  [[params.widgets.homepage]]
    type = "tag-cloud"
    
  [params.article]
    toc = true
    readingTime = true

[outputs]
  home = ["HTML", "RSS", "JSON"]